### ISSUE TITLE
上报家庭维修后，操作不够友好

### ISSUE THREAD

**Issue by anyboo** [HYCTech/CamelWX#3]
@HYCTech/hyc 
这个是用户提出的问题，我帮忙提交一下；
我们先找些其他的软件的操作方式，一起讨论一下更好的用户操作
![wechatimg15](https://user-images.githubusercontent.com/2034799/36460615-207a7f1e-16f4-11e8-9d0d-49ac4324e4a8.jpeg)

**Comment by wwxlan** [comment]
不能批量上传图片，有横竖图片时，布局没有统一布局排列，上传图片也没有压缩，淘宝的这种介面是否可以参考。提交报修成功，应该退出返回上一级菜单，要不会造成用户重复点击提交。
![_20180303164642](https://user-images.githubusercontent.com/36729834/36932390-366982a4-1f03-11e8-8d97-c600f8debefb.jpg)
![_20180303164651](https://user-images.githubusercontent.com/36729834/36932393-3e87c004-1f03-11e8-8d18-0207bea2a517.jpg)
